/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register with email and password / 註冊帳密帳號
         * @description 建立帳密帳號，並設定 access 與 refresh HttpOnly JWT Cookie。
         */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login with email and password / 帳密登入
         * @description 驗證帳密，並設定 access 與 refresh HttpOnly JWT Cookie。
         */
        post: operations["AuthController_loginWithPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user / 取得目前使用者
         * @description 驗證 access JWT，並查詢目前使用者。
         */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh JWT / 更新 Token
         * @description 驗證 refresh HttpOnly Cookie，重新簽發 access 與 refresh JWT。
         */
        post: operations["AuthTokenController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout / 登出
         * @description 清除目前瀏覽器的 access 與 refresh Cookie。已簽發的 JWT 仍會在到期時失效。
         */
        post: operations["AuthTokenController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start Google OAuth / 啟動 Google OAuth
         * @description 以瀏覽器導頁啟動 OAuth；returnTo 僅接受站內相對路徑。
         */
        get: operations["OAuthController_googleLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OAuthController_googleStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OAuthController_googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start GitHub OAuth / 啟動 GitHub OAuth
         * @description 以瀏覽器導頁啟動 OAuth；returnTo 僅接受站內相對路徑。
         */
        get: operations["OAuthController_githubLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/github/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OAuthController_githubStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OAuthController_githubCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get users / 取得使用者列表
         * @description Get a paginated list of users.
         *
         *       分頁取得使用者列表。
         */
        get: operations["UsersController_findAll"];
        put?: never;
        /**
         * Create user / 建立使用者
         * @description Create a new user.
         *
         *     建立一個新的使用者。
         */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user / 取得使用者
         * @description Get a user by ID.
         *
         *     根據使用者 ID 取得單一使用者資料。
         */
        get: operations["UsersController_findById"];
        put?: never;
        post?: never;
        /**
         * Delete user / 刪除使用者
         * @description Delete a user by ID.
         *
         *     根據使用者 ID 刪除使用者。
         */
        delete: operations["UsersController_remove"];
        options?: never;
        head?: never;
        /**
         * Update user / 更新使用者
         * @description Update an existing user by ID.
         *
         *     根據使用者 ID 更新使用者資料。
         */
        patch: operations["UsersController_update"];
        trace?: never;
    };
    "/api/roles/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 取得目前登入者的角色
         * @description 取得目前登入者在所有 App 底下的角色。
         */
        get: operations["UserRolesController_getMyRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 取得指定使用者的角色
         * @description 取得指定使用者在所有 App 底下的角色，需要管理員權限。
         */
        get: operations["UserRolesController_findByUser"];
        put?: never;
        /**
         * 指派角色給使用者
         * @description 將指定角色授予目標使用者，需要管理員權限。
         */
        post: operations["UserRolesController_assign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/users/{userId}/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 移除使用者角色
         * @description 撤銷目標使用者的指定角色，需要管理員權限。
         */
        delete: operations["UserRolesController_revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/file/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create R2 upload URL
         * @description 建立 Cloudflare R2 Presigned Upload URL。前端取得 URL 後直接將檔案上傳至 R2。需要登入才能取得上傳授權。
         */
        post: operations["FileController_createUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/file/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Create R2 download URL
         * @description 建立 Cloudflare R2 Presigned Download URL，用於存取 Private Bucket 中的檔案。
         */
        get: operations["FileController_createDownloadUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/file/relation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get files by relation
         * @description 取得指定資源所關聯的 File Metadata。
         */
        get: operations["FileController_findByRelation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/file/object/{objectKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get file metadata by object key
         * @description 依 R2 Object Key 取得 File Metadata。
         */
        get: operations["FileController_findByObjectKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/file/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get file metadata
         * @description 取得指定 File Metadata。
         */
        get: operations["FileController_findById"];
        put?: never;
        post?: never;
        /**
         * Soft delete file
         * @description 軟刪除 File Metadata。R2 實際檔案不會立即刪除，後續由 purge 流程清理。
         */
        delete: operations["FileController_softDelete"];
        options?: never;
        head?: never;
        /**
         * Update file metadata
         * @description 更新指定 File Metadata。
         */
        patch: operations["FileController_update"];
        trace?: never;
    };
    "/api/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get active files
         * @description 取得目前尚未軟刪除的 File Metadata。
         */
        get: operations["FileController_findActive"];
        put?: never;
        /**
         * Create file metadata
         * @description 建立 File Metadata。此 API 僅建立資料庫 Metadata，不負責實際 R2 上傳。需要登入才能建立。
         */
        post: operations["FileController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification/app/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user app notifications
         * @description 取得指定使用者的 App Notification，依建立時間由新到舊排序。
         */
        get: operations["NotificationController_findAppNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification/app/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get app notification
         * @description 取得指定的 App Notification。
         */
        get: operations["NotificationController_findAppNotification"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification/app": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create app notification
         * @description 建立一筆 App Notification，供 Notification Center 顯示。
         */
        post: operations["NotificationController_createAppNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification/app/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Mark app notification as read
         * @description 將指定的 App Notification 標記為已讀。
         */
        patch: operations["NotificationController_markAppNotificationAsRead"];
        trace?: never;
    };
    "/api/notification/email-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get email notification logs
         * @description 取得 Email Notification Log，依建立時間由新到舊排序。
         */
        get: operations["NotificationController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification/email-logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get email notification log
         * @description 取得指定的 Email Notification Log。
         */
        get: operations["NotificationController_findEmailNotificationLogByPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PasswordRegisterDto: {
            /**
             * Format: email
             * @description 帳號 Email。
             * @example user@example.com
             */
            email: string;
            /**
             * @description 帳號密碼。
             * @example StrongPassword123!
             */
            password: string;
            /**
             * @description 顯示名稱。
             * @example Jane Doe
             */
            name?: string;
        };
        PasswordLoginDto: {
            /**
             * Format: email
             * @description 帳號 Email。
             * @example user@example.com
             */
            email: string;
            /**
             * @description 帳號密碼。
             * @example StrongPassword123!
             */
            password: string;
        };
        AssignRoleDto: {
            /**
             * Format: uuid
             * @description 要指派的角色 ID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            roleId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordRegisterDto"];
            };
        };
        responses: {
            /** @description 帳號建立並登入成功。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 請求資料格式錯誤。 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email 已存在。 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_loginWithPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordLoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AuthTokenController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token 更新成功。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refresh Token 缺失、無效或過期。 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthTokenController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 登入 Cookie 已清除。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OAuthController_googleLogin: {
        parameters: {
            query?: {
                returnTo?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 導向 Google OAuth。 */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OAuthController_googleStart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OAuthController_googleCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 設定 JWT Cookie 並導回前端。 */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description OAuth 或 state 驗證失敗。 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OAuthController_githubLogin: {
        parameters: {
            query?: {
                returnTo?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 導向 GitHub OAuth。 */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OAuthController_githubStart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OAuthController_githubCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 設定 JWT Cookie 並導回前端。 */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description OAuth 或 state 驗證失敗。 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findAll: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    UsersController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    UsersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    UserRolesController_getMyRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得目前登入者角色成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 未登入或登入憑證無效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserRolesController_findByUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 目標使用者 ID */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得使用者角色成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 使用者 ID 格式錯誤 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 未登入或登入憑證無效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 沒有管理員權限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserRolesController_assign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 目標使用者 ID */
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRoleDto"];
            };
        };
        responses: {
            /** @description 角色指派成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 使用者 ID 或請求資料格式錯誤 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 未登入或登入憑證無效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 沒有管理員權限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserRolesController_revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 目標使用者 ID */
                userId: string;
                /** @description 要移除的角色 ID */
                roleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 未登入或登入憑證無效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FileController_createUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description File upload information */
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description 原始檔名
                     * @example example.png
                     */
                    fileName: string;
                    /**
                     * @description File MIME Type
                     * @example image/png
                     */
                    contentType?: string;
                    /**
                     * @description Presigned URL 有效時間，單位為秒
                     * @default 600
                     * @example 600
                     */
                    expiresIn?: number;
                };
            };
        };
        responses: {
            /** @description 成功建立 R2 Presigned Upload URL。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access token is missing, invalid, or expired. / 未登入或 Access Token 無效。 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FileController_createDownloadUrl: {
        parameters: {
            query: {
                /** @description R2 Object Key */
                objectKey: string;
                /** @description Presigned URL 有效時間，單位為秒 */
                expiresIn?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功建立 R2 Presigned Download URL。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FileController_findByRelation: {
        parameters: {
            query: {
                /** @description 關聯資源類型 */
                relationType: string;
                /** @description 關聯資源 ID */
                relationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功取得關聯檔案。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FileController_findByObjectKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description R2 Object Key */
                objectKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功取得 File Metadata。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 找不到指定的 File Metadata。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FileController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description File Metadata ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功取得 File Metadata。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 找不到指定的 File Metadata。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FileController_softDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description File Metadata ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功軟刪除 File Metadata。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 找不到指定的 File Metadata。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FileController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description File Metadata ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功更新 File Metadata。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 找不到指定的 File Metadata。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FileController_findActive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功取得 File Metadata。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FileController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description File Metadata */
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description R2 Object Key
                     * @example uploads/2026/09/example.png
                     */
                    objectKey: string;
                    /**
                     * @description R2 Bucket ID
                     * @example private
                     */
                    bucketId?: string | null;
                    /**
                     * @description 使用者上傳時的原始檔名
                     * @example example.png
                     */
                    originalName?: string | null;
                    /**
                     * @description 檔案 MIME Type
                     * @example image/png
                     */
                    mimeType?: string | null;
                    /**
                     * Format: int64
                     * @description 檔案大小，單位為 bytes
                     * @example 182034
                     */
                    bytes?: number | null;
                    /**
                     * @description R2 Object ETag
                     * @example "d41d8cd98f00b204e9800998ecf8427e"
                     */
                    etag?: string | null;
                    /**
                     * @description 檔案內容 Checksum
                     * @example sha256:abc123...
                     */
                    checksum?: string | null;
                    /**
                     * @description 關聯資源類型
                     * @example drawer
                     */
                    relationType?: string | null;
                    /**
                     * @description 關聯資源 ID
                     * @example 550e8400-e29b-41d4-a716-446655440000
                     */
                    relationId?: string | null;
                };
            };
        };
        responses: {
            /** @description 成功建立 File Metadata。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access token is missing, invalid, or expired. / 未登入或 Access Token 無效。 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationController_findAppNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 使用者 ID */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功取得使用者的 App Notification。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationController_findAppNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description App Notification ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功取得 App Notification。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 找不到指定的 App Notification。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationController_createAppNotification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description App Notification 資料 */
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description 接收通知的使用者 ID
                     * @example 550e8400-e29b-41d4-a716-446655440000
                     */
                    userId: string;
                    /**
                     * @description 通知類型
                     * @example comment_mention
                     */
                    type: string;
                    /**
                     * @description 通知標題
                     * @example Someone mentioned you
                     */
                    title: string;
                    /**
                     * @description 通知內容
                     * @example You were mentioned in a comment.
                     */
                    body?: string | null;
                    /**
                     * @description 點擊通知後前往的前端 Path
                     * @example /project/video?contentId=123&commentId=456
                     */
                    linkPath: string;
                    /**
                     * @description 觸發通知的使用者 ID
                     * @example 550e8400-e29b-41d4-a716-446655440000
                     */
                    actorUserId?: string | null;
                    /**
                     * @description 觸發者顯示名稱快照
                     * @example John
                     */
                    actorLabel?: string | null;
                };
            };
        };
        responses: {
            /** @description 成功建立 App Notification。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationController_markAppNotificationAsRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description App Notification ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功將通知標記為已讀。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 找不到指定的 App Notification。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功取得 Email Notification Log。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationController_findEmailNotificationLogByPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Email Notification Log ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功取得 Email Notification Log。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 找不到指定的 Email Notification Log。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
